# Generated by Django 4.1.4 on 2023-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ad_link", models.CharField(max_length=400, unique=True)),
                ("brand", models.CharField(default="", max_length=200)),
                ("model", models.CharField(default="", max_length=200)),
                ("mileage", models.IntegerField(default=0)),
                ("year", models.IntegerField(default=0)),
                ("platform", models.CharField(max_length=200)),
                ("gearbox", models.CharField(max_length=200)),
                ("price", models.FloatField(default=0)),
                ("fiscal_power", models.FloatField(default=0)),
                ("first_hand", models.BooleanField(default=True)),
            ],
        ),
    ]
