# Generated by Django 4.1.7 on 2023-03-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("car_ads", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ad", name="first_hand",),
        migrations.AddField(
            model_name="ad",
            name="fh",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ad",
            name="fiscal_power",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ad",
            name="gearbox",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ad",
            name="mileage",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ad",
            name="platform",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ad",
            name="price",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="ad",
            name="year",
            field=models.CharField(default="", max_length=200),
        ),
    ]
